README.md
build.gradle
src/main/java/com/webank/weid/demo/command/BaseBean.java
src/main/java/com/webank/weid/demo/command/BeanConstant.java
src/main/java/com/webank/weid/demo/command/DemoBase.java
src/main/java/com/webank/weid/demo/command/DemoCommand.java
src/main/java/com/webank/weid/demo/command/DemoService.java
src/main/java/com/webank/weid/demo/command/DemoTest.java
src/main/java/com/webank/weid/demo/command/DemoUtil.java
src/main/java/com/webank/weid/demo/common/dto/PasswordKey.java
src/main/java/com/webank/weid/demo/common/util/FileUtil.java
src/main/java/com/webank/weid/demo/common/util/PrivateKeyUtil.java
src/main/java/com/webank/weid/demo/common/util/PropertiesUtils.java
src/main/java/com/webank/weid/demo/controller/DemoController.java
src/main/java/com/webank/weid/demo/exception/BusinessException.java
src/main/java/com/webank/weid/demo/server/MultiConnectionSupport.java
src/main/java/com/webank/weid/demo/service/DemoService.java
src/main/java/com/webank/weid/demo/service/impl/DemoServiceImpl.java
src/main/resources/applicationContext.xml
src/main/resources/log4j2.xml

* 删除BaseBean中没有使用到的方法
* file工具类合并处理
* 优化sdk私钥获取处理
* 适配新模式的cpt
* 添加全量测试类入口
* 调整首页md说明文档表格样式

weidentity-sample adapts CPT, optimizes format, annotations and logs, and adds full-scale testing

---

sample-ci.sh
src/main/java/com/webank/weid/demo/command/DemoCommand.java
src/main/resources/weidentity.properties

add sample-ci.sh

---

build.gradle

adapt gradle 5.0

---

README.md
docs/experience-by-command.md
docs/experience-by-springboot.md

modify weid-sample docs

---

docs/zh_CN/README.rst
docs/zh_CN/docs/experience-by-command.rst
docs/zh_CN/docs/experience-by-springboot.rst
docs/zh_CN/index.rst

modify sample docs

---

src/main/java/com/webank/weid/demo/command/DemoCommand.java
src/main/java/com/webank/weid/demo/command/DemoService.java
src/main/java/com/webank/weid/demo/command/DemoTest.java
src/main/java/com/webank/weid/demo/service/impl/DemoServiceImpl.java
src/main/java/com/webank/weid/demo/service/impl/PolicyServiceImpl.java

1. 修复SetPublicKeyArgs 对type设置问题

fix set type for setPublicKey

---

sample-ci.sh

modify sample ci

---

build.gradle
sample-ci.sh
src/main/java/com/webank/weid/demo/command/DemoCommand.java
src/main/java/com/webank/weid/demo/command/DemoService.java
src/main/java/com/webank/weid/demo/server/MultiConnectionSupport.java
src/main/resources/application.properties
src/main/resources/fisco.properties.tpl

1. 修改sdk版本号
2. 放开sample-ci
3. 修复sdk1.3.2的兼容问题
4. 修改端口为6100/6101

fixed sdk version0819 

---

sample-ci.sh

adapt the fisco-bcos2.0

---

build.gradle

fixed the jackson version

---

build.gradle
claim/JsonSchema2.json
claim/JsonSchema3.json
src/main/java/com/webank/weid/demo/command/MultiGroupEvidenceSample.java
src/main/java/com/webank/weid/demo/command/TransportaionIssuer.java
src/main/java/com/webank/weid/demo/command/TransportationVerifier.java
src/main/java/com/webank/weid/demo/config/WebConfig.java
src/main/java/com/webank/weid/demo/filter/XssFilter.java
src/main/java/com/webank/weid/demo/filter/XssHttpServletRequestWraper.java

* upgrade jar and add XssFilter

---

build.gradle
sample-ci.sh

* Adapted the weid sdk 1.6.5 rc6
* modified the ci script

modified the ci script

---

build.gradle

* modify version

---

README.md
build.gradle

* adapt sdk 1.6.6

---

README.md
build.gradle
src/main/resources/.gitkeep

* upgradle weid-java-sdk 1.6.7

---

src/main/resources/.gitkeep

* remove the dir

---

README.md
build.gradle

* adpat weid-java-sdk 1.7.1

---

src/main/java/com/webank/weid/demo/command/DemoTest.java

修改createEcKeyPair方法

---

src/main/java/com/webank/weid/demo/common/util/PropertiesUtils.java
src/main/java/com/webank/weid/demo/service/impl/DemoServiceImpl.java
src/main/java/com/webank/weid/demo/service/impl/ToolServiceImpl.java

修复createWeId方法

---

README.md

增加weid各组件版本兼容说明链接
